"""Regression checks for slideshow scheduling and stable toolbar geometry."""

from __future__ import annotations

import importlib.util
import re
import sys
import tempfile
import time
from pathlib import Path
from types import SimpleNamespace

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "CrowEyes_Image_Viewer_1.7.py"


def load_viewer_module():
    spec = importlib.util.spec_from_file_location("croweyes_v17_slideshow_check", SOURCE)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot import {SOURCE}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    module.load_settings = lambda: {
        **module.DEFAULT_SETTINGS,
        "auto_register_associations": False,
        "slideshow_ms": 60,
        "list_mode": "small",
        "window_geometry": "1200x760",
    }
    module.save_settings = lambda _settings: None
    return module


def pump(viewer, milliseconds: int) -> None:
    deadline = time.monotonic() + milliseconds / 1000
    while time.monotonic() < deadline:
        viewer.update()
        time.sleep(0.01)


def main() -> None:
    module = load_viewer_module()
    with tempfile.TemporaryDirectory(prefix="croweyes-slideshow-check-") as tmp:
        folder = Path(tmp)
        files = []
        for number in range(3):
            path = folder / f"slide-{number + 1}.png"
            Image.new("RGB", (40, 30), (60 + number * 40, 90, 130)).save(path)
            files.append(path)

        viewer = module.CrowEyesImageViewer()
        viewer.geometry("1200x760")
        assert viewer.title() == module.APP_TITLE
        viewer.current_folder = folder
        viewer.folder_files = files
        viewer.index = 0
        viewer._populate_list_names_only()
        viewer._select_list_index(0)
        load_count = [0]
        viewer._load_current = lambda: load_count.__setitem__(0, load_count[0] + 1)
        viewer._queue_thumbs_priority = lambda: None
        pump(viewer, 30)

        # F5 must start a persistent timer rather than being cancelled by the
        # deferred list-selection event generated by the slideshow itself.
        viewer.event_generate("<F5>")
        pump(viewer, 190)
        assert viewer._is_slideshow(), "F5 slideshow stopped unexpectedly"
        assert viewer.slideshow_job is not None, "next slideshow tick was not scheduled"
        assert load_count[0] >= 2, f"slideshow tick count was too low: {load_count[0]}"
        assert viewer._slide_btn.cget("style") == "Accent.Icon.Tool.TButton"

        # The toolbar callback must stop rather than first interrupting and
        # then immediately starting a new slideshow.
        viewer._slide_btn.invoke()
        pump(viewer, 30)
        assert not viewer._is_slideshow(), "toolbar slideshow button did not pause slideshow"
        assert viewer.slideshow_job is None
        viewer.event_generate("<F5>")
        pump(viewer, 30)
        assert viewer._is_slideshow(), "F5 did not restart slideshow"
        viewer.event_generate("<F5>")
        pump(viewer, 30)
        assert not viewer._is_slideshow(), "second F5 did not pause slideshow"

        # Filename changes may be arbitrarily long, but primary/action button
        # positions must remain fixed because the brand area has a fixed size.
        viewer.update_idletasks()
        assert len(viewer._toolbar_buttons) >= 12
        assert viewer._brand_label.cget("text") == "CrowEyes"
        assert viewer._icons["eye"].width() == 66
        assert viewer._icons["eye"].height() == 44
        assert all(hasattr(button, "_croweyes_tooltip") for button in viewer._toolbar_buttons)
        assert all(not re.search(r"[가-힣]", str(button.cget("text"))) for button in viewer._toolbar_buttons), "toolbar contains Korean text"
        assert "Ctrl+O" in viewer._toolbar_buttons[0]._croweyes_tooltip.text
        hover_button = viewer._toolbar_buttons[0]
        hover_geometry = (hover_button.winfo_x(), hover_button.winfo_y(), hover_button.winfo_width(), hover_button.winfo_height())
        hover_button.event_generate("<Enter>")
        viewer.update_idletasks()
        assert hover_button.cget("style") == "Icon.Tool.TButton"
        assert (hover_button.winfo_x(), hover_button.winfo_y(), hover_button.winfo_width(), hover_button.winfo_height()) == hover_geometry
        viewer._toolbar_buttons[0].event_generate("<Leave>")
        viewer.update_idletasks()
        assert viewer._toolbar_buttons[0].cget("style") == "Icon.Tool.TButton"
        viewer._toolbar_buttons[0]._croweyes_tooltip._display()
        viewer.update_idletasks()
        assert viewer._toolbar_buttons[0]._croweyes_tooltip.tip is not None
        viewer._toolbar_buttons[0]._croweyes_tooltip._hide()
        buttons_before = tuple(button.winfo_rootx() for button in viewer._toolbar_buttons)
        viewer._current_path_var.set("C:\\very-long-folder-name\\" * 20 + "image.png")
        viewer.update_idletasks()
        buttons_after = tuple(button.winfo_rootx() for button in viewer._toolbar_buttons)
        assert buttons_after == buttons_before, (buttons_before, buttons_after)
        assert all(left < right for left, right in zip(buttons_after, buttons_after[1:]))
        gaps = [
            right.winfo_rootx() - (left.winfo_rootx() + left.winfo_width())
            for left, right in zip(viewer._toolbar_buttons, viewer._toolbar_buttons[1:])
        ]
        assert max(gaps) <= 16, gaps  # deliberate 4px button gaps and 14px separators
        assert viewer._toolbar_buttons[-1].winfo_rootx() + viewer._toolbar_buttons[-1].winfo_width() < viewer.winfo_rootx() + viewer.winfo_width()
        assert viewer._icons["previous"].width() == 20
        toolbar_images = {str(button.cget("image")) for button in viewer._toolbar_buttons}
        assert str(viewer._icons["previous"]) not in toolbar_images
        assert str(viewer._icons["next"]) not in toolbar_images
        assert viewer._icons["eye"].width() == 66
        assert viewer.toolbar.winfo_rooty() < viewer.navigation_bar.winfo_rooty()
        viewer.toggle_image_fullscreen()
        pump(viewer, 20)
        viewer.toggle_image_fullscreen()
        pump(viewer, 20)
        assert viewer.toolbar.winfo_rooty() < viewer.navigation_bar.winfo_rooty(), "fullscreen restore swapped chrome rows"

        # The responsive command row must still fit at the declared
        # minimum window width without hiding the final overflow menu.
        viewer.geometry("860x520")
        pump(viewer, 30)
        toolbar_right = viewer._toolbar_buttons[-1].winfo_rootx() + viewer._toolbar_buttons[-1].winfo_width()
        assert toolbar_right <= viewer.winfo_rootx() + viewer.winfo_width(), toolbar_right
        assert viewer._zoom_label.winfo_rootx() > viewer.status.winfo_rootx()
        assert viewer._path_label.winfo_rootx() > viewer._zoom_label.winfo_rootx()
        assert viewer._brightness_scale.winfo_rootx() > viewer._path_label.winfo_rootx()
        assert viewer._brightness_scale.winfo_width() <= 60
        assert viewer._contrast_scale.winfo_width() <= 60
        viewer.set_ui_theme("bright_sky_blue")
        pump(viewer, 80)
        toolbar_right = viewer._toolbar_buttons[-1].winfo_rootx() + viewer._toolbar_buttons[-1].winfo_width()
        assert toolbar_right <= viewer.winfo_rootx() + viewer.winfo_width(), "theme rebuild lost responsive layout"
        assert viewer._toolbar_buttons[-1].winfo_ismapped(), "More menu disappeared after theme rebuild"

        # Pixel color is shown as RGB hexadecimal and zoom has its own stable
        # field immediately before the full path.
        viewer.display_image = Image.new("RGB", (40, 30), (0x12, 0x34, 0x56))
        viewer.zoom = 1.0
        viewer.offset_x = viewer.offset_y = 0.0
        viewer.redraw()
        viewer.update_idletasks()
        assert viewer._canvas_prev_btn.winfo_ismapped()
        assert viewer._canvas_next_btn.winfo_ismapped()
        before_edge_geometry = (
            viewer._canvas_prev_btn.winfo_width(), viewer._canvas_prev_btn.winfo_height(),
        )
        viewer._canvas_prev_btn.event_generate("<Enter>")
        viewer.update_idletasks()
        assert (viewer._canvas_prev_btn.winfo_width(), viewer._canvas_prev_btn.winfo_height()) == before_edge_geometry
        viewer._canvas_prev_btn.event_generate("<Leave>")
        assert viewer._top_search.winfo_height() <= 30
        assert hasattr(viewer, "_playlist_close_btn")
        assert not hasattr(viewer, "_playlist_summary_var")
        viewer._on_motion(SimpleNamespace(
            x=viewer.canvas.winfo_width() / 2,
            y=viewer.canvas.winfo_height() / 2,
        ))
        assert "#123456" in viewer.status.cget("text")
        assert viewer._zoom_text_var.get() == "크기 100%"
        viewer.zoom_by(1.15)
        assert viewer._zoom_text_var.get() == "크기 115%"
        viewer.destroy()

    print("PASS: slideshow F5 timer and fixed toolbar geometry")


if __name__ == "__main__":
    main()
